name: Update Holidays JSON

on:
  schedule:
    - cron: "0 0 * * *" # 毎日9時(JST) → UTC0時
  workflow_dispatch: # 手動実行も可能

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリ取得
        uses: actions/checkout@v3

      - name: 祝日データ取得
        run: |
          curl -s https://holidays-jp.github.io/api/v1/date.json -o json/holidays.json

      - name: 差分チェック
        id: diff
        run: |
          if git diff --quiet json/holidays.json; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: コミット＆プッシュ
        if: steps.diff.outputs.no_changes == 'false'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add json/holidays.json
          git commit -m "Update holidays.json"
          git push